### ISSUE TITLE
Issue with DefinePlugin

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/quinoa-design-library#3]
```
/tests/quinoa/quinoa-design-library/node_modules/webpack/lib/DefinePlugin.js:51
        compiler.hooks.compilation.tap(
                       ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/tests/quinoa/quinoa-design-library/node_modules/webpack/lib/DefinePlugin.js:51:18)
    at Compiler.apply (/tests/quinoa/quinoa-design-library/node_modules/@storybook/core/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/tests/quinoa/quinoa-design-library/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/tests/quinoa/quinoa-design-library/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/tests/quinoa/quinoa-design-library/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/tests/quinoa/quinoa-design-library/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tests/quinoa/quinoa-design-library/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```

**Comment by robindemourat** [comment]
Probably related to this : https://github.com/storybooks/storybook/issues/3083
